### Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a = a.transpose()

In [6]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [7]:
a[0:,1:]

array([[ 2,  3,  3,  1],
       [ 8, 11, 10,  7]])

In [8]:
a_1 = a[0:1]

In [9]:
a_1

array([[1, 2, 3, 3, 1]])

In [10]:
a_2 = a[1:2]

In [11]:
a_1 = a_1[0]

In [12]:
a_2 = a_2[0]

In [22]:
a = a.transpose()

In [23]:
a_1

array([1, 2, 3, 3, 1])

In [24]:
mean_a =[a_1.mean(), a_2.mean()]

In [25]:
mean_a

[2.0, 8.4]

### Задание 2

In [32]:
a_centered = a - mean_a

In [33]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [45]:
a_centered_sp = a_centered[0:,:1][0] @ a_centered[0:,1:][0]

In [52]:
a_centered_sp / (5 - 1)

0.6000000000000001

### Задание  4

In [57]:
np.cov(a_1, a_2)

array([[1. , 2. ],
       [2. , 4.3]])

In [56]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])